# Generated by Django 4.2.28 on 2026-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='อีเมล')),
                ('position', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Intern', 'Intern')], max_length=50, verbose_name='ตำแหน่งงาน')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึก')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'ข้อมูลพนักงาน',
                'ordering': ['-created_at'],
            },
        ),
    ]
