# Generated by Django 4.2.28 on 2026-02-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('age', models.IntegerField(verbose_name='อายุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่บันทึก')),
            ],
            options={
                'verbose_name': 'ข้อมูลประชากร',
                'verbose_name_plural': 'ข้อมูลประชากร',
                'ordering': ['-created_at'],
            },
        ),
    ]
